Universe              = vanilla
executable            = runEfficienciesQED.sh
arguments             = $(ProcId) 0 
GetEnv                = True
output                = output/$(ClusterId).$(ProcId).out
error                 = error/$(ClusterId).$(ProcId).err
log                   = log/$(ClusterId).log
requirements 	      = (OpSysAndVer =?= "CentOS7")
+JobFlavour           = "tomorrow"

## data (0)
#queue 10400
queue 5272

## MC SC (1)
#queue 256

## MC SL (2)
#queue 242
