Universe              = vanilla
executable            = runPrepareBasicPlots.sh
arguments             = $(ProcId) 0 4
GetEnv                = True
output                = output/$(ClusterId).$(ProcId).out
error                 = error/$(ClusterId).$(ProcId).err
log                   = log/$(ClusterId).log
requirements 	      = (OpSysAndVer =?= "CentOS7")
+JobFlavour           = "longlunch"
queue 60
