Universe              = vanilla
executable            = runSelectAnomalousEvents_qqbar.sh
arguments             = $(ProcId) 1 
GetEnv                = True
output                = output/$(ClusterId).$(ProcId).out
error                 = error/$(ClusterId).$(ProcId).err
log                   = log/$(ClusterId).log
requirements 	      = (OpSysAndVer =?= "CentOS7")
+JobFlavour           = "tomorrow"

## ccbar (0)
#queue 10400
#queue 30

## bbbar (1)
queue 51

