Universe              = vanilla
executable            = runTauTauApplySelection.sh
arguments             = $(ProcId) $(ClusterId)
GetEnv                = True
output                = output/$(ClusterId).$(ProcId).out
error                 = error/$(ClusterId).$(ProcId).err
log                   = log/$(ClusterId).log
requirements          = (OpSysAndVer =?= "CentOS7")
+JobFlavour           = "espresso"
queue 5600

